https://pytorch.org/docs/stable/generated/torch.nn.Module.html

https://pytorch.org/docs/stable/nn.html

https://pytorch.org/docs/stable/nn.html

https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html

In [1]:
import torch

X = torch.Tensor([
                    [0, 0],
                    [0, 1],
                    [1, 0],
                    [1, 1]
                  ])

Y = torch.Tensor([
                    [0],
                    [1],
                    [1],
                    [0]
                  ])

print(X,"\n")
print(Y)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]]) 

tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [2]:
import torch.nn as nn
import torch.nn.functional as F

class XOR(nn.Module):
    def __init__(self):
        super(XOR, self).__init__()
        self.lin1 = nn.Linear(2, 3, True)
        self.lin2 = nn.Linear(3, 1, True)

    def forward(self, x):
        x = self.lin1(x)
        x = F.relu(x)
        x = self.lin2(x)
        return x


In [3]:
model = XOR()

In [4]:
import torch.optim as optim
loss_func = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01,momentum=0.75)

In [5]:
epochs = 5001
for idx in range(0, epochs):
    for x,y in zip(X,Y):
        optimizer.zero_grad()       # Zero the gradient buffers
        y_hat = model(x)            # Make predictions
        loss = loss_func(y_hat, y)  # Compute the loss
        loss.backward()             # Compute the gradients
        optimizer.step()            # Does the update

In [6]:
model(X).relu()

tensor([[7.7486e-07],
        [1.0000e+00],
        [1.0000e+00],
        [8.6427e-07]], grad_fn=<ReluBackward0>)

In [7]:
@torch.no_grad()
def init_weights(m):
    m_class = m.__class__.__name__
    if m_class.find('Linear') != -1:
        m.weight.data.uniform_(0.0,1.0)
        m.bias.data.fill_(0)

In [8]:
model = XOR()
model.apply(init_weights)

XOR(
  (lin1): Linear(in_features=2, out_features=3, bias=True)
  (lin2): Linear(in_features=3, out_features=1, bias=True)
)

In [9]:
loss_func = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01,momentum=0.75)

In [10]:
epochs = 5001
for idx in range(0, epochs):
    for x,y in zip(X,Y):
        optimizer.zero_grad()       # Zero the gradient buffers
        y_hat = model(x)            # Make predictions
        loss = loss_func(y_hat, y)  # Compute the loss
        loss.backward()             # Compute the gradients
        optimizer.step()            # Does the update

In [11]:
model(X).relu()

tensor([[1.5738e-06],
        [1.0000e+00],
        [1.0000e+00],
        [6.5381e-07]], grad_fn=<ReluBackward0>)

In [12]:
@torch.no_grad()
def init_weights(m):
    m_class = m.__class__.__name__
    if m_class.find('Linear') != -1:
        m.weight.data.uniform_(0.0,0.1)
        m.bias.data.fill_(0)

In [14]:
model = XOR()
model.apply(init_weights)

XOR(
  (lin1): Linear(in_features=2, out_features=3, bias=True)
  (lin2): Linear(in_features=3, out_features=1, bias=True)
)

In [18]:
dtype = torch.float
loss_func = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)
epochs = 5001
lambda1 = 0.5
L1_regularization = torch.tensor(0,dtype=dtype)

In [19]:
for idx in range(0, epochs):
    for x,y in zip(X,Y):
        optimizer.zero_grad()           # Zero the gradient buffers
        y_hat = model(x)                # Make predictions
        MSE_loss = loss_func(y_hat, y)  # Compute the loss 
        loss = MSE_loss + lambda1 * (L1_regularization - 0.5) 
        loss.backward()                 # Compute the gradients
        optimizer.step()                # Does the update
        
        with torch.no_grad():
            for param in model.parameters():
                L1_regularization += torch.sum(torch.abs(param))

In [20]:
model(X).relu()

tensor([[4.7449e-06],
        [1.0000e+00],
        [1.0000e+00],
        [1.1026e-06]], grad_fn=<ReluBackward0>)

Naoaki Okazaki, “Introduction to Deep Learning Feedforward Neural Networks,” 2020 [Online]. https://chokkan.github.io/deeplearning/binary-impl.html [Accessed August 30th, 2020].

In [21]:
import torch

dtype = torch.float

# Training data for XOR.
x = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=dtype)
y = torch.tensor([[0], [1], [1], [0]], dtype=dtype)
                                        
# Define a neural network using high-level modules.
model = torch.nn.Sequential(
    torch.nn.Linear(2, 2, bias=True),   # 2 dims (with bias) -> 2 dims
    torch.nn.Sigmoid(),                 # Sigmoid function
    torch.nn.Linear(2, 1, bias=True),   # 2 dims (with bias) -> 1 dim
)

# Binary corss-entropy loss after sigmoid function.
loss_fn = torch.nn.BCEWithLogitsLoss(size_average=False)

eta = 0.5
for t in range(1000):
    y_pred = model(x)                   # Make predictions.
    loss = loss_fn(y_pred, y)           # Compute the loss.    
    model.zero_grad()                   # Zero-clear the gradients.
    loss.backward()                     # Compute the gradients.
        
    with torch.no_grad():
        for param in model.parameters():
            param -= eta * param.grad   # Update the parameters using SGD.

C:\Users\ZellaDaGod\.conda\envs\PyTorch\lib\site-packages\torch\nn\_reduction.py:44: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [22]:
model(x).sigmoid()

tensor([[0.0050],
        [0.9945],
        [0.9945],
        [0.0084]], grad_fn=<SigmoidBackward>)